[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Zhuoran He <zhuo1angT@Outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ascii_utils = "0.9.3"